[tool.poetry]
name = "onlinestoree"
name = "pyproject-toml"
version = "0.1.0"
description = ""
authors = ["none"]
readme = "README.md"
packages = [{include = "pyproject"}]


[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.4"
ipython = "^9.13.0
pillow = "^12.2.0"
python-dotenv = "^1.2.2"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"
black = "^26.3.1"
isort = "^8.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
line_length = 119


[tool.black]
line-length = 119
