# Generated by Django 6.0.4 on 2026-05-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок блога', max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст блога', verbose_name='Контент')),
                ('image', models.ImageField(blank=True, help_text='Загрузите превью блога', null=True, upload_to='images/', verbose_name='Превью')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('publication_sign', models.BooleanField(verbose_name='Признак публикации')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
