# Generated by Django 6.0.4 on 2026-05-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['created_at'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='article',
        ),
    ]
